const RouteName = {
    SPLSH: "SplashScreen",
    SWIPER_SCREEN: "Swiperscreen",
    LOGIN_SCREEN: "LoginScreen",
    FORGET_PASSWORD: "ForgotPassword",
    REGISTER_SCREEN: "Register",
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
    HOME_SCREEN: "HomeScreen",
    REGIATRAION_SUCCESSFULL: "RegistrationSuccessful",
    TRANSLATION_SCREEN: "TranslationScreen",
    HOME_TAB: 'Homes',
    EVENT_TAB: 'Event',
    EVENT_AROUND_MAP: 'Events Around',
    BOOKMARK_TAB: 'Bookmarks',
    PROFILE_TAB: 'Profile',
    SELECT_LOCATION: 'SelectLocation',
    NOTIFICATION_SCREEN: 'NotificationScreen',
    TRENDING_SCREEN: 'TrendingScreen',
    SEARCH_SCREEN: 'SearchScreen',
    EVENTS_DETAILS_SCREEN: 'EventsDetails',
    CHAT_SCREEN: 'ChatScreen',
    ORGAIZER_SCREEN: 'OrganizerScreen',
    BUY_TICKET_SCREEN: 'BuyTicketScreen',
    PAYMENT_SCREEN: 'PaymentScreen',
    PAYMENT_SUCCESSFULL: 'PaymentSuccessFully',
    EVENT_LIST_SCREEN: 'EventListScreen',
    ADD_EVENT_SCREEN: 'Add Events',
    TICKET_SCREEN: 'TicketScreen',
    REVIEWS_SCREEN: 'ReviewsScreen',
    HELP_SCREEN: 'HelpScreen',
    FAQ_SCREEN: 'FAQScreen',
    SCAN_SCREEN: 'Scanner',
    SETTING_SCREEN: 'SettingsScreen',
}
export default RouteName;